name = "wx-api"
main = "dist/index.js"
compatibility_date = "2024-12-27"

routes = [
  { pattern = "your.domain.com", custom_domain = true }
]

kv_namespaces = [
  { binding = "pgyh", id = "2097a73a271e4ebda65d303915b5af65" }
]

[ai]
binding = "AI"

[vars]
AppID = "wx1763dce290fb74d8"
AppToken = "microtech123"
AppSecret = "5d8389c5f877"
AppAesKey = "07cf50a1f17a4849290ed2cbcf5aa26c"
AesMode = "OFF"
InitAuth = "your-init-auth"
AllowOrigin = "your-front-allow-list"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 60, period = 60 }
